# @package _global_

defaults:
  - _self_

# 仿真环境配置
sim:
  device: "cuda:0"
  dt: 0.01
  robot: "franka_panda"
  num_envs: 1
  item_id: 100392

runner:
  max_steps_per_round: 200
  total_rounds: 10

# 模型配置 (必须与训练时一致)
path:
  checkpoint_path: "/media/hhhar/hhd/har/vlddd/cps/2025_12_01_20:47/checkpoint_epoch_105_0.3008.pth"  # 替换为你训练好的权重路径
  action_stats_path: "/home/hhhar/liuliu/vld/dataset/action_stats.json"   # 替换为你的统计量文件路径
  
  # 网络参数
model:
  action_dim: 7
  chunk_size: 10
  num_action_bins: 256
  text_model_name: "bert-base-uncased"
  rgb_dim: 2048
  pc_feature_dim: 1024
  text_dim: 768
  diffusion_hidden_dim: 512
  diffusion_layers: 6

# 推理策略
inference:
  num_steps: 10       # Diffusion 去噪步数
  execution_horizon: 4 # Receding Horizon: 每次推理预测10步，但只执行前4步，然后重新推理